create schema prjc13;
use prjc13;

CREATE TABLE ROL (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    codRol CHAR(2) NOT NULL, 
    descRol VARCHAR(200) NOT NULL, 
    estaActivo BOOLEAN NOT NULL
);

CREATE TABLE USUARIO (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    idRol INT NOT NULL,
    codUsuario VARCHAR(8) NOT NULL, 
    contrasen VARCHAR(20) NOT NULL, 
    correo VARCHAR(200) NOT NULL, 
    estaActivo BOOLEAN NOT NULL
);

ALTER TABLE USUARIO
	ADD CONSTRAINT FK_USUARIO_ROL
		FOREIGN KEY USUARIO(idRol) REFERENCES ROL(id);

CREATE TABLE PRODUCTO (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    codProducto CHAR(8) NOT NULL, 
    nomProducto VARCHAR(80) NOT NULL, 
    descProducto VARCHAR(200) NOT NULL, 
    cantProducto INT NOT NULL,
    precProducto DECIMAL(5, 2) NOT NULL, 
    estaActivo BOOLEAN NOT NULL
);

CREATE TABLE CLIENTE (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    idUsuario INT NOT NULL,
    dni CHAR(8) NOT NULL, 
    nombres VARCHAR(80) NOT NULL, 
    apePaterno VARCHAR(80) NOT NULL, 
    apeMaterno VARCHAR(80) NOT NULL, 
    fechaNacimiento DATE NOT NULL
);

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_USUARIO
		FOREIGN KEY CLIENTE(idUsuario) REFERENCES USUARIO(id);

CREATE TABLE CARRITO (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idCliente INT NOT NULL,
    numCarrito INT NOT NULL,
    fecha DATE NOT NULL,
    total DECIMAL(5,2),
    igv DECIMAL(4,2)
);

ALTER TABLE CARRITO
	ADD CONSTRAINT FK_CARRITO_CLIENTE
		FOREIGN KEY CARRITO(idCliente) REFERENCES CLIENTE(id);

CREATE TABLE LINEACARRITO (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    idCarrito INT NOT NULL, 
    lineaCarrito INT NOT NULL,
    idProducto INT NOT NULL, 
    cantidad INT NOT NULL, 
    total DECIMAL(5, 2) NOT NULL
);

ALTER TABLE LINEACARRITO 
	ADD CONSTRAINT FK_LINEACARRITO_CARRITO
		FOREIGN KEY LINEACARRITO(idCarrito) REFERENCES CARRITO(id); 

ALTER TABLE LINEACARRITO
	ADD CONSTRAINT FK_LINEACARRITO_PRODUCTO
		FOREIGN KEY LINEACARRITO(idProducto) REFERENCES PRODUCTO(id);
        
CREATE TABLE DOCVENTA (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    numVenta INT NOT NULL, 
    idCarrito INT NOT NULL, 
    fecha DATE NOT NULL, 
    subTotal DECIMAL(5, 2) NOT NULL, 
    igv DECIMAL(5, 2) NOT NULL, 
    total DECIMAL(5, 2) NOT NULL
);

ALTER TABLE DOCVENTA
	ADD CONSTRAINT DOCVENTA
		FOREIGN KEY DOCVENTA(idCarrito) REFERENCES CARRITO(id);

CREATE TABLE LINEADOCVENTA (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    idDocVenta INT NOT NULL, 
    idLineaCarrito INT NOT NULL,
    idProducto INT NOT NULL, 
    cantidad INT NOT NULL, 
    subTotal DECIMAL(5, 2) NOT NULL
);

ALTER TABLE LINEADOCVENTA
	ADD CONSTRAINT FK_LINEADOCVENTA_DOCVENTA
		FOREIGN KEY LINEAORDEN(idDocVenta) REFERENCES DOCVENTA(id);
        
ALTER TABLE LINEADOCVENTA
	ADD CONSTRAINT FK_LINEADOCVENTA_LINEACARRITO
		FOREIGN KEY LINEAORDEN(idLineaCarrito) REFERENCES LINEACARRITO(id);
        
ALTER TABLE LINEADOCVENTA
	ADD CONSTRAINT FK_LINEADOCVENTA_PRODUCTO
		FOREIGN KEY LINEAORDEN(idProducto) REFERENCES PRODUCTO(id);